### PR TITLE
dd Multipart Upload mode for libs3

### PR DESCRIPTION
**Pull request by chenji-kael**
when file size is larger than 15M, this
mode will be active

Signed-off-by: chenji <insomnia@139.com>

### CODE REVIEW

**Comment by bji** [comment]
Wow, thank you very much for this awesome change!

One small request: I worked hard to keep the code to within 80 columns width; it's one of the rules of code formatting that I try to follow.  Would it be possible for you to reformat the code to fit 80 columns?  I can do it too if it's too much trouble for you.

Still reviewing the change, but at first glance it looks great!  Thanks again!

**Comment by bji** [comment]
Another comment - I changed the license to LGPL a while ago, but the new files in this change have a GPL copyright.  Can you please change to LGPL?  An example header to include would be the one from src/object.c.

**Comment by bji** [comment]
What does "#define _XOPEN_SOURCE 500" do in src/s3.c?  I google searched and it's still not exactly clear to me why this is needed now, and even if it is, everything I read said to set it to 600, not 500.

**Comment by bji** [comment]
Please update the function comment for growbuffer_append as it appears to now return a number of bytes, not just "nonzero on success, zero on out of memory".  It would be good to document exactly what the meaning of the nonzero return value is.

**Comment by bji** [comment]
How does a user cancel a multi part upload in progress?  I see that they can use S3_multipart_initial to start the multipart upload and S3_multipart_upload_part to add parts, and then S3_multipart_commit to complete the upload, but what if they want to abort a multipart upload in progress?  Is something like S3_multipart_abort necessary?

Also, how is a user notified when a part of a multipart commit has completed uploading?  If I have a 15 GB file, I don't want to break it up into 15 MB chunks and immediately call S3_multipart_upload_part for every chunk, I want to add chunks as previous chunks complete.  Isn't a per-part callback necessary too to let the user know when parts have completed uploading?  Or maybe this is already happening via the S3PutObjectHandler's responseHandler's completeCallback as specified for each part?  If so, I don't see that documented anywhere.

Finally - isn't one of the purposes of multipart upload to be able to continue an upload that was interrupted without having to re-upload already-completed parts?  Wouldn't that imply that an API for querying S3 to see what parts of an upload have already been committed on the S3 side?  So shouldn't this API include the "List Parts" and "List Multipart Uploads" features as described on this page:

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRESTAPImpUpload.html

**Comment by bji** [comment]
You'll note that all of the public API defined in libs3.h is very thoroughly commented; I think these added functions need similar documentation:

S3_multipart_initial
S3_multipart_upload_part
S3_multipart_commit

(I'm guessing this is what that TODO comment is about; but the documentation should be in the change before the change can be accepted, thanks!)

**Comment by chenji-kael** [comment]
@bji "#define _XOPEN_SOURCE 500" is used for strdup ,otherwise will be a warning ,I think 600 also OK
man strdup: strdup(): _SVID_SOURCE || _BSD_SOURCE || _XOPEN_SOURCE >= 500

**Comment by chenji-kael** [comment]
@bji ping ,HI,more functions  have been added, and I only do some simple test that have passed

**Comment by bji** [comment]
Thank you, I will review the change in more thorough detail tomorrow.

**Comment by bji** [comment]
Thank you for your additional changes, they look great.

**Pull request merged**
