### PR TITLE
Fix urlencode error according to AWS S3 documents.

### PR DESCRIPTION
**Pull request by likema**
See also: http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html

### CODE REVIEW

**Comment by bji** [comment]
Can you please change the name of sort_and_urlencode_query_string since it no longer does any url encoding?  It should now be named sort_query_string.  Thanks!

**Comment by likema** [comment]
Fixed.

**Comment by bji** [comment]
Thank you!

**Comment by likema** [comment]
You are welcome!

2017年5月26日 下午11:39，"bji" <notifications@github.com>写道：

**Pull request merged**
